server:
  port: 8083
  servlet:
    context-path: /interest/user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: interest-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interest_user?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    # Hikari 连接池配置，号称史上最快连接池。并且在springboot2.0之后，采用的默认数据库连接池就是Hikari
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 连接池最大连接数，默认是10
      maximum-pool-size: 15
      # 指定校验连接合法性执行的sql语句
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 连接池名称
      pool-name: DatebookHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 5000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000ms
  liquibase:
    change-log: classpath:database/master.xml
    enabled: true
    drop-first: false
logging:
# 你需要存储日志的目录
  file: F:/interest/file/log/interest-user.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest.user: DEBUG
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.user.model